### ISSUE TITLE
recovering change points 

### ISSUE THREAD

**Issue by andrewcztrack** [pmorenoz/continual_ihcpd#1]
hi @pmorenoz !!

Really cool project.

I was just wondering if you can recover change points using the algorithm.

ie "if change point do action"

Kind regards,
Andrew

**Comment by pmorenoz** [comment]
Hi @andrewcztrack, thanks for your interest.
Sure, you can take actions if a change-point is detected or not. For instance, in the file "ihcpd.py" in this repo, after the L115 (self.r_map[t] = maxes[t + 1]), you can do something like:

if self.r_map[t] < 7: # MAP estimate says that it was a change in the last 7 days, 7 time-steps, ...
        do_action()..

another example would be with (self.r_map[t] == 0) but it means that you detected the change-point with absolute no delay, what in practice is very difficult (the change has to be suuuper huge).

I hope that this things fit with the ideas you are trying to develop. 

Cheers, 
Pablo 

> hi @pmorenoz !!
> Really cool project.
> I was just wondering if you can recover change points using the algorithm.
> ie "if change point do action"
> Kind regards,
> Andrew

**Comment by pmorenoz** [comment]
answered
